name: "generate-docs"
on:
  pull_request:
    types: [closed]

jobs:
  generate-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
      with:
          go-version: 1.16.5
          stable: true
      - name: gendocs
        run: |
          ./hack/generate_docs.sh ${{ secrets.MINIKUBE_BOT_PAT }}
