name: "generate-docs"
on:
  push:
    branch:
      - master  

jobs:
  generate-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
          stable: true
      - name: gendocs
        run: |
          ./hack/generate_docs.sh ${{ secrets.MINIKUBE_BOT_PAT }}
